---
abstract: 'CPAN 中国作者'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Chinese
provides:
  Acme::CPANAuthors::Chinese:
    file: lib/Acme/CPANAuthors/Chinese.pm
    version: 0.18
requires:
  Acme::CPANAuthors: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.18
